name: lesson4
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.7.0
  intl: ^0.18.1
  arkit_plugin: ^1.0.7
  http: ^0.13.6
  lazy_load_scrollview: ^1.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/prof.jpg 
